name: Feilrapport
description: Rapporter en feil du har oppdaget i Krono
title: "[Feil]: "
labels: ["bug"]

body:
  - type: textarea
    id: bug-description
    attributes:
      label: "Beskriv feilen"
      description: "En tydelig beskrivelse av hva feilen er."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steg for å reprodusere"
      description: "Beskriv stegene for å gjenskape feilen."
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: "Nettleser"
      description: "Hvilken nettleser bruker du?"
      options:
        - Chrome
        - Firefox
        - Brave
        - Safari
        - Edge
        - Opera
        - Annen
    validations:
      required: true
  - type: checkboxes
    id: deployment-type
    attributes:
      label: "Installasjonstype"
      description: "Velg hvilken type Krono-installasjon du bruker."
      options:
        - label: Docker
        - label: Standalone
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Forventet oppførsel"
      description: "En tydelig beskrivelse av hva du forventet skulle skje."
    validations:
      required: false
  - type: textarea
    id: docker-logs
    attributes:
      label: "Krono-logger"
      description: "Kjør `docker logs krono` for Docker. Kopier og lim inn relevant logg her. Dette formateres automatisk som kode."
      render: shell
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: "Skjermbilder"
      description: "Legg ved skjermbilder hvis det er relevant for å forklare problemet."
    validations:
      required: false
