name: Ny funksjonalitet
description: Foreslå en ny funksjon for Krono
title: "[Ny funksjonalitet]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    id: instructions
    attributes:
      value: "## Takk for at du vil forbedre Krono! Fyll inn så mye informasjon som mulig i feltene under.\n"

  - type: input
    id: feature_short_description
    attributes:
      label: "Kort oppsummering"
      description: "Gi en kort oppsummering av funksjonen."
    validations:
      required: true

  - type: textarea
    id: feature_detailed_description
    attributes:
      label: "Detaljert beskrivelse"
      description: "Beskriv den foreslåtte funksjonen i detalj. Inkluder hva den skal gjøre, hvordan den skal fungere, og hvilke fordeler den gir."
    validations:
      required: false

  - type: textarea
    id: use_case
    attributes:
      label: "Bruksområde"
      description: "Beskriv bruksområdet eller problemet denne funksjonen løser."
    validations:
      required: false

  - type: dropdown
    id: willing_to_contribute
    attributes:
      label: "Villig til å bidra"
      description: "Er du villig til å bidra med utvikling eller testing av denne funksjonen?"
      options:
        - "Ja, jeg kan hjelpe med koding"
        - "Ja, jeg kan hjelpe med testing"
        - "Nei, jeg kan kun foreslå funksjonen"
    validations:
      required: false
